export enum ActionTypes {
    ADD_FAVORITE_CAR = 'ADD_FAVORITE_CAR',
    GET_FAVORITE_LIST = 'GET_FAVORITE_LIST',
    UPDATE_MARQUE = 'UPDATE_MARQUE',
    DELETE_MARQUE = 'DELETE_MARQUE',
    UPDATE_FAVORITES = 'UPDATE_FAVORITES',
}